### ISSUE TITLE
Unable to import solcjs

### ISSUE THREAD

**Issue by jacquesd** [Giveth/solcpiler#18]
Since the npm dependency `solc` (aka `solcjs`) has been [moved from `dependencies`, to `devDependencies`](https://github.com/Giveth/solcpiler/commit/8833ae961af881569dab76a6c779a71d9f8b61fc), when installing solcpiler, `solcjs` may be fully absent.

In this case the [`solcjs` import](https://github.com/Giveth/solcpiler/blob/master/js/solcpiler.js#L4) will fail.

The quick fix would be to move solcjs back as a dependency.

There may be a  better fix which would to detect if `solcjs` is present or not with something like:

``` js
let solc;
try { solc = require('solcjs'); } 
catch(err) { solc = null; }
```

But I am not sure how to then handle the fetching of the request version.  Namely how to execute the following without `solcjs`:
``` js
this.solc.loadRemoteVersion(...);
```

There is also the problem of figuring out which version to load if no version is required.

**Comment by perissology** [comment]
Actually, I should have moved it to peerDependencies so you get a warning on install. This way we don't need to always have the most up-to-date version of solcjs in the dependencies.

However it is a bit of an inconvenience, and probably better to just leave as a dependency.
